// Location data for programmatic SEO
// Each location generates pages for all services (12 services × 188 locations = 2,256 pages)

export type Location = {
  slug: string;
  name: string;
  county: string;
  isCounty?: boolean; // true for county-level locations like Essex
  nearbyAreas: string[]; // slugs of nearby locations for internal linking
  localHook: string; // unique sentence fragment for content differentiation
  postcodeAreas?: string[]; // postcode coverage
  // Optional: area-specific pain points (drives conversions)
  commonProblems?: string[]; // e.g., "coastal salt residue", "clay soil stains"
};

export const locations: Location[] = [
  // County-level location (appears first for SEO priority)
  {
    slug: 'essex',
    name: 'Essex',
    county: 'Essex',
    isCounty: true,
    nearbyAreas: ['chelmsford', 'southend-on-sea', 'colchester', 'basildon', 'brentwood', 'harlow', 'romford', 'saffron-walden'],
    localHook: 'across the entire county from Southend to Harlow',
    commonProblems: ['coastal weather damage', 'rural mud and dirt', 'urban pollution buildup'],
  },
  {
    slug: 'basildon',
    name: 'Basildon',
    county: 'Essex',
    nearbyAreas: ['wickford', 'billericay', 'pitsea', 'laindon'],
    localHook: 'from Basildon town centre to the surrounding neighbourhoods',
    postcodeAreas: ['SS13', 'SS14', 'SS15', 'SS16'],
    commonProblems: ['high foot traffic stains', 'pet odours', 'end of tenancy cleaning'],
  },
  {
    slug: 'southend-on-sea',
    name: 'Southend-on-Sea',
    county: 'Essex',
    nearbyAreas: ['westcliff-on-sea', 'leigh-on-sea', 'thorpe-bay', 'shoeburyness'],
    localHook: 'along the seafront and throughout the town',
    postcodeAreas: ['SS0', 'SS1', 'SS2', 'SS3', 'SS9'],
    commonProblems: ['salt residue from sea air', 'sand tracked indoors', 'seagull mess on roofs'],
  },
  {
    slug: 'chelmsford',
    name: 'Chelmsford',
    county: 'Essex',
    nearbyAreas: ['writtle', 'broomfield', 'springfield', 'great-baddow'],
    localHook: 'across the city centre and residential areas',
    postcodeAreas: ['CM1', 'CM2', 'CM3'],
    commonProblems: ['moss and algae buildup', 'leaf stains on patios', 'clay soil marks'],
  },
  {
    slug: 'brentwood',
    name: 'Brentwood',
    county: 'Essex',
    nearbyAreas: ['shenfield', 'hutton', 'pilgrims-hatch', 'warley'],
    localHook: 'throughout the town and surrounding villages',
    postcodeAreas: ['CM13', 'CM14', 'CM15'],
    commonProblems: ['large driveways needing refresh', 'tree sap on patios', 'green algae on render'],
  },
  {
    slug: 'billericay',
    name: 'Billericay',
    county: 'Essex',
    nearbyAreas: ['basildon', 'wickford', 'stock', 'great-burstead'],
    localHook: 'from the High Street to the surrounding residential areas',
    postcodeAreas: ['CM11', 'CM12'],
    commonProblems: ['moss on roof tiles', 'blocked gutters', 'weathered patio slabs'],
  },
  {
    slug: 'wickford',
    name: 'Wickford',
    county: 'Essex',
    nearbyAreas: ['basildon', 'rayleigh', 'billericay', 'shotgate'],
    localHook: 'across the town and neighbouring communities',
    postcodeAreas: ['SS11', 'SS12'],
  },
  {
    slug: 'rayleigh',
    name: 'Rayleigh',
    county: 'Essex',
    nearbyAreas: ['hockley', 'rochford', 'wickford', 'hullbridge'],
    localHook: 'from the historic High Street to modern estates',
    postcodeAreas: ['SS6'],
  },
  {
    slug: 'benfleet',
    name: 'Benfleet',
    county: 'Essex',
    nearbyAreas: ['canvey-island', 'thundersley', 'hadleigh', 'south-benfleet'],
    localHook: 'serving both South Benfleet and the surrounding area',
    postcodeAreas: ['SS7'],
  },
  {
    slug: 'canvey-island',
    name: 'Canvey Island',
    county: 'Essex',
    nearbyAreas: ['benfleet', 'thundersley', 'hadleigh'],
    localHook: 'across the entire island community',
    postcodeAreas: ['SS8'],
    commonProblems: ['island flooding risk leaving silt on ground floors', 'sea wall salt spray on windows', 'estuary damp accelerating mould indoors'],
  },
  {
    slug: 'grays',
    name: 'Grays',
    county: 'Essex',
    nearbyAreas: ['tilbury', 'stanford-le-hope', 'chafford-hundred', 'south-ockendon'],
    localHook: 'throughout Grays and Thurrock',
    postcodeAreas: ['RM17', 'RM20'],
    commonProblems: ['A13 traffic soot settling on render', 'Thames-side humidity accelerating mould', 'industrial area dust coating windows'],
  },
  {
    slug: 'stanford-le-hope',
    name: 'Stanford-le-Hope',
    county: 'Essex',
    nearbyAreas: ['grays', 'corringham', 'tilbury', 'horndon-on-the-hill'],
    localHook: 'serving Stanford-le-Hope and Corringham',
    postcodeAreas: ['SS17'],
  },
  {
    slug: 'tilbury',
    name: 'Tilbury',
    county: 'Essex',
    nearbyAreas: ['grays', 'stanford-le-hope', 'chadwell-st-mary'],
    localHook: 'across the Tilbury area',
    postcodeAreas: ['RM18'],
  },
  {
    slug: 'leigh-on-sea',
    name: 'Leigh-on-Sea',
    county: 'Essex',
    nearbyAreas: ['southend-on-sea', 'westcliff-on-sea', 'hadleigh', 'benfleet'],
    localHook: 'from Old Leigh to the Broadway',
    postcodeAreas: ['SS9'],
    commonProblems: ['Old Leigh harbour salt air on windows', 'sand tracked up from the beach into carpets', 'seafront damp accelerating patio moss'],
  },
  {
    slug: 'westcliff-on-sea',
    name: 'Westcliff-on-Sea',
    county: 'Essex',
    nearbyAreas: ['southend-on-sea', 'leigh-on-sea', 'prittlewell'],
    localHook: 'along the clifftop and surrounding streets',
    postcodeAreas: ['SS0'],
    commonProblems: ['clifftop wind driving salt onto render', 'sea air damp causing window frame grime', 'north-facing cliffs trapping moss on walls'],
  },
  {
    slug: 'rochford',
    name: 'Rochford',
    county: 'Essex',
    nearbyAreas: ['rayleigh', 'hockley', 'southend-on-sea', 'great-wakering'],
    localHook: 'throughout the historic market town',
    postcodeAreas: ['SS4'],
    commonProblems: ['river Roach damp encouraging indoor mould', 'market town foot traffic wearing shop carpets', 'low-lying area flooding leaving mud residue'],
  },
  {
    slug: 'hockley',
    name: 'Hockley',
    county: 'Essex',
    nearbyAreas: ['rayleigh', 'rochford', 'hullbridge', 'hawkwell'],
    localHook: 'across Hockley and Hawkwell',
    postcodeAreas: ['SS5'],
  },
  {
    slug: 'maldon',
    name: 'Maldon',
    county: 'Essex',
    nearbyAreas: ['heybridge', 'burnham-on-crouch', 'witham', 'danbury'],
    localHook: 'from the historic Hythe to the town centre',
    postcodeAreas: ['CM9'],
    commonProblems: ['Blackwater estuary salt air on windows', 'Hythe waterfront humidity accelerating algae', 'tidal mud tracked from riverside walks'],
  },
  {
    slug: 'witham',
    name: 'Witham',
    county: 'Essex',
    nearbyAreas: ['braintree', 'maldon', 'kelvedon', 'hatfield-peverel'],
    localHook: 'throughout the town and surrounding villages',
    postcodeAreas: ['CM8'],
  },
  {
    slug: 'braintree',
    name: 'Braintree',
    county: 'Essex',
    nearbyAreas: ['witham', 'halstead', 'coggeshall', 'bocking'],
    localHook: 'across Braintree and Bocking',
    postcodeAreas: ['CM7'],
  },
  {
    slug: 'colchester',
    name: 'Colchester',
    county: 'Essex',
    nearbyAreas: ['wivenhoe', 'west-mersea', 'stanway', 'brightlingsea', 'dedham', 'marks-tey', 'rowhedge', 'tiptree'],
    localHook: 'across Britain\'s oldest recorded town',
    postcodeAreas: ['CO1', 'CO2', 'CO3', 'CO4'],
    commonProblems: ['Roman wall stonework staining', 'university term-end carpet wear', 'garrison area soot buildup'],
  },
  {
    slug: 'clacton-on-sea',
    name: 'Clacton-on-Sea',
    county: 'Essex',
    nearbyAreas: ['frinton-on-sea', 'walton-on-the-naze', 'jaywick', 'holland-on-sea'],
    localHook: 'along the coast and throughout the town',
    postcodeAreas: ['CO15', 'CO16'],
    commonProblems: ['sea salt film on windows and frames', 'beach sand tracked deep into hallway carpets', 'coastal damp feeding moss on north-facing roofs'],
  },
  {
    slug: 'harlow',
    name: 'Harlow',
    county: 'Essex',
    nearbyAreas: ['epping', 'north-weald', 'ongar'],
    localHook: 'across all areas of the new town',
    postcodeAreas: ['CM17', 'CM18', 'CM19', 'CM20'],
    commonProblems: ['new town block paving sprouting weeds fast', 'construction dust in recently built homes', 'flat terrain rain pooling causing patio algae'],
  },
  {
    slug: 'epping',
    name: 'Epping',
    county: 'Essex',
    nearbyAreas: ['harlow', 'loughton', 'theydon-bois', 'north-weald'],
    localHook: 'from the High Street to the forest edges',
    postcodeAreas: ['CM16'],
    commonProblems: ['Epping Forest leaf fall clogging gutters', 'tree canopy shade accelerating roof moss', 'forest pollen coating windows and driveways'],
  },
  {
    slug: 'loughton',
    name: 'Loughton',
    county: 'Essex',
    nearbyAreas: ['chigwell', 'buckhurst-hill', 'epping', 'woodford'],
    localHook: 'throughout Loughton and Debden',
    postcodeAreas: ['IG10'],
    commonProblems: ['forest-edge leaf debris blocking gutters every autumn', 'tree canopy shade driving moss on north-facing roofs', 'sap and bird droppings staining driveways'],
  },
  {
    slug: 'chigwell',
    name: 'Chigwell',
    county: 'Essex',
    nearbyAreas: ['loughton', 'woodford', 'buckhurst-hill', 'hainault'],
    localHook: 'across Chigwell and Grange Hill',
    postcodeAreas: ['IG7', 'IG8'],
    commonProblems: ['tree-lined roads shedding leaves into gutters', 'sap and pollen staining block paving', 'shade from mature gardens causing rapid moss growth'],
  },
  // Additional Essex Towns
  {
    slug: 'saffron-walden',
    name: 'Saffron Walden',
    county: 'Essex',
    nearbyAreas: ['great-dunmow', 'braintree', 'halstead'],
    localHook: 'throughout the historic market town and surrounding villages',
    postcodeAreas: ['CB10', 'CB11'],
    commonProblems: ['thatched roof moss and lichen', 'lime mortar sensitivity on old walls', 'pollen buildup from surrounding farmland'],
  },
  {
    slug: 'great-dunmow',
    name: 'Great Dunmow',
    county: 'Essex',
    nearbyAreas: ['saffron-walden', 'braintree', 'chelmsford', 'harlow'],
    localHook: 'across the town and nearby villages',
    postcodeAreas: ['CM6'],
  },
  {
    slug: 'halstead',
    name: 'Halstead',
    county: 'Essex',
    nearbyAreas: ['braintree', 'colchester', 'saffron-walden'],
    localHook: 'throughout Halstead and the Colne Valley',
    postcodeAreas: ['CO9'],
  },
  {
    slug: 'burnham-on-crouch',
    name: 'Burnham-on-Crouch',
    county: 'Essex',
    nearbyAreas: ['maldon', 'southminster', 'rochford'],
    localHook: 'along the waterfront and throughout the town',
    postcodeAreas: ['CM0'],
    commonProblems: ['Crouch estuary salt air corroding gutters', 'river humidity accelerating algae on render', 'tidal mud tracked from waterfront onto floors'],
  },
  {
    slug: 'frinton-on-sea',
    name: 'Frinton-on-Sea',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'walton-on-the-naze', 'colchester'],
    localHook: 'from the Greensward to the residential streets',
    postcodeAreas: ['CO13'],
    commonProblems: ['sea salt damage', 'sand accumulation', 'coastal weather exposure'],
  },
  {
    slug: 'walton-on-the-naze',
    name: 'Walton-on-the-Naze',
    county: 'Essex',
    nearbyAreas: ['frinton-on-sea', 'clacton-on-sea', 'colchester'],
    localHook: 'across the seaside town and surrounding area',
    postcodeAreas: ['CO14'],
    commonProblems: ['Naze cliff salt spray corroding gutters', 'coastal wind driving sand into carpet pile', 'seafront humidity accelerating roof moss'],
  },
  {
    slug: 'manningtree',
    name: 'Manningtree',
    county: 'Essex',
    nearbyAreas: ['colchester', 'harwich', 'dedham', 'lawford'],
    localHook: 'throughout Britain\'s smallest town and nearby Mistley',
    postcodeAreas: ['CO11'],
  },
  // Colchester area locations
  {
    slug: 'wivenhoe',
    name: 'Wivenhoe',
    county: 'Essex',
    nearbyAreas: ['colchester', 'brightlingsea', 'rowhedge', 'alresford'],
    localHook: 'across the historic port town and university area',
    postcodeAreas: ['CO7'],
    commonProblems: ['river Colne damp causing indoor mould', 'student flat end-of-tenancy carpet stains', 'tidal mud tracked onto driveways'],
  },
  {
    slug: 'west-mersea',
    name: 'West Mersea',
    county: 'Essex',
    nearbyAreas: ['colchester', 'brightlingsea', 'rowhedge', 'tollesbury'],
    localHook: 'across Mersea Island and the waterfront',
    postcodeAreas: ['CO5'],
    commonProblems: ['salt spray corroding guttering', 'coastal wind driving sand into carpet pile', 'island humidity accelerating moss growth'],
  },
  {
    slug: 'stanway',
    name: 'Stanway',
    county: 'Essex',
    nearbyAreas: ['colchester', 'copford', 'marks-tey', 'tiptree'],
    localHook: 'throughout Stanway and the retail park area',
    postcodeAreas: ['CO3'],
    commonProblems: ['construction dust settling in new-build carpets', 'block paving weed growth within two years', 'render staining quickly on new estates'],
  },
  {
    slug: 'brightlingsea',
    name: 'Brightlingsea',
    county: 'Essex',
    nearbyAreas: ['colchester', 'wivenhoe', 'west-mersea', 'thorrington'],
    localHook: 'across the sailing town and harbour area',
    postcodeAreas: ['CO7'],
    commonProblems: ['harbour salt spray on windows', 'algae growth from estuary humidity', 'boat yard dust settling on patios'],
  },
  {
    slug: 'dedham',
    name: 'Dedham',
    county: 'Essex',
    nearbyAreas: ['colchester', 'manningtree', 'ardleigh', 'lawford'],
    localHook: 'in the heart of Constable Country',
    postcodeAreas: ['CO7'],
    commonProblems: ['river Stour damp encouraging moss on roofs', 'country lane mud tracked onto floors', 'listed building lime mortar sensitivity'],
  },
  {
    slug: 'marks-tey',
    name: 'Marks Tey',
    county: 'Essex',
    nearbyAreas: ['colchester', 'stanway', 'copford', 'kelvedon'],
    localHook: 'across the village and commuter area',
    postcodeAreas: ['CO6'],
    commonProblems: ['railway soot settling on render', 'A12 road film on windows and gutters', 'heavy goods traffic vibration loosening roof moss'],
  },
  {
    slug: 'rowhedge',
    name: 'Rowhedge',
    county: 'Essex',
    nearbyAreas: ['colchester', 'wivenhoe', 'fingringhoe', 'abberton'],
    localHook: 'along the River Colne waterfront',
    postcodeAreas: ['CO5'],
    commonProblems: ['River Colne damp accelerating mould', 'tidal flood residue on ground floors', 'riverside moss on north-facing walls'],
  },
  {
    slug: 'great-horkesley',
    name: 'Great Horkesley',
    county: 'Essex',
    nearbyAreas: ['colchester', 'boxted', 'west-bergholt', 'dedham'],
    localHook: 'throughout the village and surrounding countryside',
    postcodeAreas: ['CO6'],
    commonProblems: ['agricultural dust coating windows and sills', 'country lane mud on driveways after rain', 'exposed hilltop wind driving moss growth'],
  },
  {
    slug: 'boxted',
    name: 'Boxted',
    county: 'Essex',
    nearbyAreas: ['colchester', 'great-horkesley', 'dedham', 'langham'],
    localHook: 'across the village and rural surroundings',
    postcodeAreas: ['CO4'],
    commonProblems: ['farmland dust settling on conservatory roofs', 'country lane mud ground into hallway carpets', 'north-facing moss from dense tree cover'],
  },
  {
    slug: 'ardleigh',
    name: 'Ardleigh',
    county: 'Essex',
    nearbyAreas: ['colchester', 'dedham', 'manningtree', 'great-bromley'],
    localHook: 'throughout the village and A12 corridor',
    postcodeAreas: ['CO7'],
    commonProblems: ['A12 road spray film on windows', 'reservoir humidity accelerating algae on patios', 'heavy rain runoff staining block paving'],
  },
  {
    slug: 'thorpe-le-soken',
    name: 'Thorpe-le-Soken',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'frinton-on-sea', 'colchester', 'weeley'],
    localHook: 'across the village and Tendring countryside',
    postcodeAreas: ['CO16'],
  },
  {
    slug: 'west-bergholt',
    name: 'West Bergholt',
    county: 'Essex',
    nearbyAreas: ['colchester', 'great-horkesley', 'marks-tey', 'fordham'],
    localHook: 'throughout the village and surrounding heathland',
    postcodeAreas: ['CO6'],
    commonProblems: ['heathland pollen coating cars and driveways', 'tree canopy shade causing rapid moss growth', 'leaf fall clogging gutters every autumn'],
  },
  {
    slug: 'layer-de-la-haye',
    name: 'Layer-de-la-Haye',
    county: 'Essex',
    nearbyAreas: ['colchester', 'abberton', 'birch', 'tiptree'],
    localHook: 'near Abberton Reservoir and the surrounding countryside',
    postcodeAreas: ['CO2'],
    commonProblems: ['reservoir humidity accelerating algae growth', 'bird droppings from nearby nature reserve', 'muddy lane runoff staining driveways'],
  },
  {
    slug: 'waltham-abbey',
    name: 'Waltham Abbey',
    county: 'Essex',
    nearbyAreas: ['epping', 'loughton', 'chingford', 'theydon-bois'],
    localHook: 'from the historic abbey to modern estates',
    postcodeAreas: ['EN9'],
  },
  {
    slug: 'ingatestone',
    name: 'Ingatestone',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'chelmsford', 'billericay'],
    localHook: 'across the village and surrounding countryside',
    postcodeAreas: ['CM4'],
  },
  {
    slug: 'south-woodham-ferrers',
    name: 'South Woodham Ferrers',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'maldon', 'wickford', 'burnham-on-crouch'],
    localHook: 'throughout the town and riverside areas',
    postcodeAreas: ['CM3'],
  },
  // Greater London Border Areas
  {
    slug: 'romford',
    name: 'Romford',
    county: 'Greater London',
    nearbyAreas: ['hornchurch', 'upminster', 'ilford', 'dagenham', 'brentwood'],
    localHook: 'across Romford and the London Borough of Havering',
    postcodeAreas: ['RM1', 'RM2', 'RM3', 'RM7'],
    commonProblems: ['A12 traffic soot on render and fascias', 'high street pollution film on shop fronts', 'heavy foot traffic staining entrance carpets'],
  },
  {
    slug: 'hornchurch',
    name: 'Hornchurch',
    county: 'Greater London',
    nearbyAreas: ['romford', 'upminster', 'rainham', 'dagenham'],
    localHook: 'throughout Hornchurch and Emerson Park',
    postcodeAreas: ['RM11', 'RM12'],
  },
  {
    slug: 'upminster',
    name: 'Upminster',
    county: 'Greater London',
    nearbyAreas: ['hornchurch', 'romford', 'grays', 'stanford-le-hope'],
    localHook: 'across Upminster and Cranham',
    postcodeAreas: ['RM14'],
  },
  {
    slug: 'ilford',
    name: 'Ilford',
    county: 'Greater London',
    nearbyAreas: ['romford', 'barking', 'woodford', 'chigwell'],
    localHook: 'across Ilford and the London Borough of Redbridge',
    postcodeAreas: ['IG1', 'IG2', 'IG3', 'IG4', 'IG5', 'IG6'],
    commonProblems: ['traffic pollution grime on windows', 'road salt staining driveways in winter', 'high-density housing trapping damp and mould'],
  },
  {
    slug: 'woodford',
    name: 'Woodford',
    county: 'Greater London',
    nearbyAreas: ['loughton', 'chigwell', 'ilford', 'wanstead'],
    localHook: 'throughout Woodford Green and South Woodford',
    postcodeAreas: ['IG8', 'E18'],
    commonProblems: ['tree-lined streets clogging gutters with leaves', 'forest-edge shade driving algae on fences', 'mature garden debris staining patios'],
  },
  {
    slug: 'barking',
    name: 'Barking',
    county: 'Greater London',
    nearbyAreas: ['dagenham', 'ilford', 'romford', 'east-ham'],
    localHook: 'across Barking and the surrounding area',
    postcodeAreas: ['IG11'],
  },
  {
    slug: 'dagenham',
    name: 'Dagenham',
    county: 'Greater London',
    nearbyAreas: ['barking', 'romford', 'hornchurch', 'rainham'],
    localHook: 'throughout Dagenham and Becontree',
    postcodeAreas: ['RM8', 'RM9', 'RM10'],
  },
  // More Local Essex Towns
  {
    slug: 'ongar',
    name: 'Ongar',
    county: 'Essex',
    nearbyAreas: ['epping', 'brentwood', 'harlow', 'ingatestone'],
    localHook: 'across Chipping Ongar and the surrounding villages',
    postcodeAreas: ['CM5'],
  },
  {
    slug: 'stansted-mountfitchet',
    name: 'Stansted Mountfitchet',
    county: 'Essex',
    nearbyAreas: ['saffron-walden', 'great-dunmow', 'takeley'],
    localHook: 'throughout the village and near Stansted Airport',
    postcodeAreas: ['CM24'],
  },
  {
    slug: 'tiptree',
    name: 'Tiptree',
    county: 'Essex',
    nearbyAreas: ['colchester', 'witham', 'kelvedon', 'maldon'],
    localHook: 'across Tiptree and the surrounding area',
    postcodeAreas: ['CO5'],
  },
  {
    slug: 'kelvedon',
    name: 'Kelvedon',
    county: 'Essex',
    nearbyAreas: ['witham', 'braintree', 'tiptree', 'colchester'],
    localHook: 'throughout Kelvedon and Feering',
    postcodeAreas: ['CO5'],
  },
  {
    slug: 'danbury',
    name: 'Danbury',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'maldon', 'south-woodham-ferrers'],
    localHook: 'across the hilltop village and surrounding countryside',
    postcodeAreas: ['CM3'],
    commonProblems: ['hilltop wind exposure driving rain into render', 'dense woodland leaf fall clogging gutters', 'clay soil staining driveways after heavy rain'],
  },
  {
    slug: 'writtle',
    name: 'Writtle',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'ingatestone', 'broomfield'],
    localHook: 'throughout the historic village',
    postcodeAreas: ['CM1'],
  },
  {
    slug: 'hadleigh',
    name: 'Hadleigh',
    county: 'Essex',
    nearbyAreas: ['benfleet', 'leigh-on-sea', 'thundersley', 'canvey-island'],
    localHook: 'from Hadleigh Castle to the town centre',
    postcodeAreas: ['SS7'],
  },
  {
    slug: 'thundersley',
    name: 'Thundersley',
    county: 'Essex',
    nearbyAreas: ['benfleet', 'hadleigh', 'rayleigh', 'canvey-island'],
    localHook: 'across Thundersley and Daws Heath',
    postcodeAreas: ['SS7'],
  },
  {
    slug: 'corringham',
    name: 'Corringham',
    county: 'Essex',
    nearbyAreas: ['stanford-le-hope', 'grays', 'tilbury', 'basildon'],
    localHook: 'throughout Corringham and Fobbing',
    postcodeAreas: ['SS17'],
  },
  {
    slug: 'pitsea',
    name: 'Pitsea',
    county: 'Essex',
    nearbyAreas: ['basildon', 'benfleet', 'canvey-island', 'wickford'],
    localHook: 'across Pitsea and the surrounding area',
    postcodeAreas: ['SS13'],
  },
  // East London Areas
  {
    slug: 'stratford',
    name: 'Stratford',
    county: 'Greater London',
    nearbyAreas: ['leyton', 'east-ham', 'ilford', 'wanstead'],
    localHook: 'across Stratford and the Olympic Park area',
    postcodeAreas: ['E15', 'E20'],
    commonProblems: ['post-construction dust in new-build carpets', 'Olympic Park pollen and tree debris', 'high-rise window grime from city air'],
  },
  {
    slug: 'walthamstow',
    name: 'Walthamstow',
    county: 'Greater London',
    nearbyAreas: ['leyton', 'leytonstone', 'chingford', 'woodford'],
    localHook: 'from the Village to Blackhorse Road',
    postcodeAreas: ['E17'],
    commonProblems: ['Victorian sash window grime buildup', 'narrow street trapping moss on north walls', 'market area foot traffic wearing carpets fast'],
  },
  {
    slug: 'leyton',
    name: 'Leyton',
    county: 'Greater London',
    nearbyAreas: ['leytonstone', 'stratford', 'walthamstow', 'leyton'],
    localHook: 'throughout Leyton and the surrounding area',
    postcodeAreas: ['E10'],
  },
  {
    slug: 'leytonstone',
    name: 'Leytonstone',
    county: 'Greater London',
    nearbyAreas: ['leyton', 'wanstead', 'ilford', 'stratford'],
    localHook: 'across Leytonstone and Bush Road area',
    postcodeAreas: ['E11'],
  },
  {
    slug: 'east-ham',
    name: 'East Ham',
    county: 'Greater London',
    nearbyAreas: ['barking', 'stratford', 'ilford', 'manor-park'],
    localHook: 'throughout East Ham and the surrounding streets',
    postcodeAreas: ['E6'],
  },
  {
    slug: 'wanstead',
    name: 'Wanstead',
    county: 'Greater London',
    nearbyAreas: ['ilford', 'leytonstone', 'woodford', 'chigwell'],
    localHook: 'across Wanstead and Snaresbrook',
    postcodeAreas: ['E11'],
  },
  // High Priority Additions
  {
    slug: 'harwich',
    name: 'Harwich',
    county: 'Essex',
    nearbyAreas: ['dovercourt', 'manningtree', 'colchester', 'frinton-on-sea'],
    localHook: 'across the historic port town and ferry terminal area',
    postcodeAreas: ['CO12'],
    commonProblems: ['sea salt corrosion', 'ferry traffic pollution', 'coastal weather exposure'],
  },
  {
    slug: 'buckhurst-hill',
    name: 'Buckhurst Hill',
    county: 'Essex',
    nearbyAreas: ['loughton', 'chigwell', 'woodford', 'theydon-bois'],
    localHook: 'throughout the affluent commuter town',
    postcodeAreas: ['IG9'],
    commonProblems: ['tree canopy shedding leaves into gutters', 'forest shade causing moss on roof tiles', 'sap and pollen staining driveways'],
  },
  {
    slug: 'shenfield',
    name: 'Shenfield',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'hutton', 'ingatestone', 'billericay'],
    localHook: 'across Shenfield and the Elizabeth Line corridor',
    postcodeAreas: ['CM15'],
  },
  {
    slug: 'chingford',
    name: 'Chingford',
    county: 'Greater London',
    nearbyAreas: ['walthamstow', 'loughton', 'woodford', 'buckhurst-hill'],
    localHook: 'from Chingford Mount to the Epping Forest edge',
    postcodeAreas: ['E4'],
    commonProblems: ['Epping Forest leaf fall blocking gutters', 'tree shade driving green algae on render', 'forest pollen coating conservatory glass'],
  },
  {
    slug: 'rainham',
    name: 'Rainham',
    county: 'Greater London',
    nearbyAreas: ['hornchurch', 'dagenham', 'grays', 'purfleet'],
    localHook: 'across Rainham and the marshes area',
    postcodeAreas: ['RM13'],
    commonProblems: ['industrial fallout film on windows', 'marshland damp accelerating mould growth', 'Thames-side salt air corroding guttering'],
  },
  {
    slug: 'great-baddow',
    name: 'Great Baddow',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'danbury', 'sandon', 'galleywood'],
    localHook: 'throughout Great Baddow and the Chelmsford suburbs',
    postcodeAreas: ['CM2'],
    commonProblems: ['established garden trees clogging gutters', 'school-run traffic grime on front driveways', 'clay soil tracked onto carpets after rain'],
  },
  {
    slug: 'broomfield',
    name: 'Broomfield',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'writtle', 'springfield', 'great-waltham'],
    localHook: 'near Broomfield Hospital and the village centre',
    postcodeAreas: ['CM1'],
  },
  {
    slug: 'springfield',
    name: 'Springfield',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'broomfield', 'boreham', 'little-waltham'],
    localHook: 'across Springfield and Barnes Mill',
    postcodeAreas: ['CM1', 'CM2'],
    commonProblems: ['river Chelmer damp on ground-floor carpets', 'new estate block paving sprouting weeds fast', 'builder dust settling in recently finished homes'],
  },
  {
    slug: 'coggeshall',
    name: 'Coggeshall',
    county: 'Essex',
    nearbyAreas: ['braintree', 'kelvedon', 'colchester', 'marks-tey'],
    localHook: 'throughout the historic wool town',
    postcodeAreas: ['CO6'],
    commonProblems: ['timber-framed buildings trapping damp and mould', 'narrow street moss on shaded walls', 'Colne Valley humidity staining render'],
  },
  {
    slug: 'shoeburyness',
    name: 'Shoeburyness',
    county: 'Essex',
    nearbyAreas: ['southend-on-sea', 'thorpe-bay', 'great-wakering', 'rochford'],
    localHook: 'from the garrison to East Beach',
    postcodeAreas: ['SS3'],
    commonProblems: ['extreme coastal salt spray on windows', 'beach sand ground deep into carpet pile', 'north-facing roofs thick with sea-damp moss'],
  },
  // Southend Area Additions
  {
    slug: 'thorpe-bay',
    name: 'Thorpe Bay',
    county: 'Essex',
    nearbyAreas: ['southend-on-sea', 'shoeburyness', 'westcliff-on-sea'],
    localHook: 'along the prestigious seafront and gardens',
    postcodeAreas: ['SS1'],
    commonProblems: ['seafront salt film on windows and frames', 'beach sand tracked through hallway carpets', 'coastal damp accelerating patio algae'],
  },
  {
    slug: 'prittlewell',
    name: 'Prittlewell',
    county: 'Essex',
    nearbyAreas: ['southend-on-sea', 'westcliff-on-sea', 'rochford', 'eastwood'],
    localHook: 'near the historic priory and town centre',
    postcodeAreas: ['SS2'],
  },
  {
    slug: 'great-wakering',
    name: 'Great Wakering',
    county: 'Essex',
    nearbyAreas: ['shoeburyness', 'rochford', 'barling', 'foulness'],
    localHook: 'across the village and nearby marshlands',
    postcodeAreas: ['SS3'],
    commonProblems: ['rural coastal exposure', 'farming area dust', 'marshland humidity'],
  },
  {
    slug: 'hullbridge',
    name: 'Hullbridge',
    county: 'Essex',
    nearbyAreas: ['rayleigh', 'hockley', 'rochford', 'south-woodham-ferrers'],
    localHook: 'along the River Crouch waterfront',
    postcodeAreas: ['SS5'],
    commonProblems: ['River Crouch damp causing indoor mould', 'riverside moss covering fences and patios', 'flood-risk area silt staining ground floors'],
  },
  {
    slug: 'hawkwell',
    name: 'Hawkwell',
    county: 'Essex',
    nearbyAreas: ['hockley', 'rayleigh', 'rochford', 'ashingdon'],
    localHook: 'throughout Hawkwell village and surroundings',
    postcodeAreas: ['SS5'],
  },
  // Thurrock Additions
  {
    slug: 'south-ockendon',
    name: 'South Ockendon',
    county: 'Essex',
    nearbyAreas: ['grays', 'upminster', 'rainham', 'aveley'],
    localHook: 'across South Ockendon and Belhus',
    postcodeAreas: ['RM15'],
  },
  {
    slug: 'chafford-hundred',
    name: 'Chafford Hundred',
    county: 'Essex',
    nearbyAreas: ['grays', 'lakeside', 'south-ockendon', 'west-thurrock'],
    localHook: 'throughout the modern Lakeside development',
    postcodeAreas: ['RM16'],
  },
  {
    slug: 'chadwell-st-mary',
    name: 'Chadwell St Mary',
    county: 'Essex',
    nearbyAreas: ['tilbury', 'grays', 'stanford-le-hope', 'orsett'],
    localHook: 'across the village and towards Tilbury',
    postcodeAreas: ['RM16'],
    commonProblems: ['Thames proximity humidity feeding mould', 'industrial area soot settling on render', 'heavy clay soil staining driveways'],
  },
  // Tendring Coast Additions
  {
    slug: 'jaywick',
    name: 'Jaywick',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'holland-on-sea', 'st-osyth'],
    localHook: 'across the coastal community',
    postcodeAreas: ['CO15'],
    commonProblems: ['extreme salt spray eroding window seals', 'coastal damp driving mould in ground-floor rooms', 'beach sand ground deep into carpet fibres'],
  },
  {
    slug: 'holland-on-sea',
    name: 'Holland-on-Sea',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'frinton-on-sea', 'great-clacton'],
    localHook: 'along the seafront and residential streets',
    postcodeAreas: ['CO15'],
    commonProblems: ['sea air corroding metal guttering', 'coastal wind driving salt onto windows', 'damp from sea proximity accelerating moss'],
  },
  {
    slug: 'dovercourt',
    name: 'Dovercourt',
    county: 'Essex',
    nearbyAreas: ['harwich', 'parkeston', 'ramsey', 'manningtree'],
    localHook: 'across Dovercourt Bay and the town centre',
    postcodeAreas: ['CO12'],
    commonProblems: ['salt spray from the bay corroding fascias', 'Victorian render trapping damp and algae', 'ferry port pollution film on windows'],
  },
  {
    slug: 'mistley',
    name: 'Mistley',
    county: 'Essex',
    nearbyAreas: ['manningtree', 'harwich', 'lawford', 'bradfield'],
    localHook: 'along the historic quayside and village',
    postcodeAreas: ['CO11'],
  },
  {
    slug: 'weeley',
    name: 'Weeley',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'thorpe-le-soken', 'great-bentley', 'little-clacton'],
    localHook: 'throughout Weeley village and Heath area',
    postcodeAreas: ['CO16'],
  },
  // Central Essex Additions
  {
    slug: 'heybridge',
    name: 'Heybridge',
    county: 'Essex',
    nearbyAreas: ['maldon', 'witham', 'tolleshunt-darcy', 'goldhanger'],
    localHook: 'from Heybridge Basin to the town centre',
    postcodeAreas: ['CM9'],
    commonProblems: ['Blackwater estuary damp accelerating moss', 'canal basin humidity staining render', 'tidal creek mud tracked onto driveways'],
  },
  {
    slug: 'southminster',
    name: 'Southminster',
    county: 'Essex',
    nearbyAreas: ['burnham-on-crouch', 'maldon', 'tillingham', 'bradwell-on-sea'],
    localHook: 'across the Dengie Peninsula village',
    postcodeAreas: ['CM0'],
    commonProblems: ['Dengie Peninsula coastal wind exposure', 'agricultural dust coating windows and roofs', 'flat terrain flooding leaving silt residue'],
  },
  {
    slug: 'hatfield-peverel',
    name: 'Hatfield Peverel',
    county: 'Essex',
    nearbyAreas: ['witham', 'chelmsford', 'maldon', 'terling'],
    localHook: 'throughout the village and station area',
    postcodeAreas: ['CM3'],
    commonProblems: ['A12 road spray film on front windows', 'train line soot settling on roofs', 'clay soil staining driveways after heavy rain'],
  },
  {
    slug: 'stock',
    name: 'Stock',
    county: 'Essex',
    nearbyAreas: ['billericay', 'ingatestone', 'chelmsford', 'galleywood'],
    localHook: 'across the picturesque village',
    postcodeAreas: ['CM4'],
    commonProblems: ['country lane mud ground into hall carpets', 'mature garden trees dropping sap on patios', 'exposed hilltop wind accelerating roof moss'],
  },
  // West Essex Additions
  {
    slug: 'theydon-bois',
    name: 'Theydon Bois',
    county: 'Essex',
    nearbyAreas: ['epping', 'loughton', 'buckhurst-hill', 'abridge'],
    localHook: 'on the edge of Epping Forest',
    postcodeAreas: ['CM16'],
    commonProblems: ['Epping Forest leaves clogging gutters every autumn', 'tree canopy shade driving moss on roofs', 'forest pollen settling on driveways and cars'],
  },
  {
    slug: 'north-weald',
    name: 'North Weald',
    county: 'Essex',
    nearbyAreas: ['epping', 'harlow', 'ongar', 'thornwood'],
    localHook: 'near the historic airfield and village',
    postcodeAreas: ['CM16', 'CM17'],
    commonProblems: ['airfield dust settling on nearby rooftops', 'market-day mud tracked onto drives and carpets', 'rural lane runoff staining paving after storms'],
  },
  {
    slug: 'hainault',
    name: 'Hainault',
    county: 'Greater London',
    nearbyAreas: ['chigwell', 'ilford', 'romford', 'woodford'],
    localHook: 'near Hainault Forest and the residential areas',
    postcodeAreas: ['IG6', 'IG7'],
    commonProblems: ['Hainault Forest leaf fall blocking gutters', 'tree shade causing green algae on fences', 'forest-edge pollen coating conservatory roofs'],
  },
  // Brentwood Area Addition
  {
    slug: 'hutton',
    name: 'Hutton',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'shenfield', 'billericay', 'ingrave'],
    localHook: 'across Hutton village and Mount area',
    postcodeAreas: ['CM13'],
  },
  // ===== Closing the Gap: All Referenced nearbyAreas =====
  // Basildon/South Essex Area
  {
    slug: 'laindon',
    name: 'Laindon',
    county: 'Essex',
    nearbyAreas: ['basildon', 'billericay', 'wickford', 'langdon-hills'],
    localHook: 'across Laindon and Langdon Hills',
    postcodeAreas: ['SS15', 'SS16'],
  },
  {
    slug: 'south-benfleet',
    name: 'South Benfleet',
    county: 'Essex',
    nearbyAreas: ['benfleet', 'canvey-island', 'hadleigh', 'thundersley'],
    localHook: 'in the heart of South Benfleet',
    postcodeAreas: ['SS7'],
  },
  {
    slug: 'eastwood',
    name: 'Eastwood',
    county: 'Essex',
    nearbyAreas: ['southend-on-sea', 'leigh-on-sea', 'rayleigh', 'prittlewell'],
    localHook: 'across Eastwood and towards Rayleigh',
    postcodeAreas: ['SS9'],
  },
  {
    slug: 'shotgate',
    name: 'Shotgate',
    county: 'Essex',
    nearbyAreas: ['wickford', 'rayleigh', 'rawreth', 'battlesbridge'],
    localHook: 'throughout Shotgate village',
    postcodeAreas: ['SS11'],
  },
  {
    slug: 'ashingdon',
    name: 'Ashingdon',
    county: 'Essex',
    nearbyAreas: ['rochford', 'hawkwell', 'hockley', 'canewdon'],
    localHook: 'across Ashingdon and the historic battlefield',
    postcodeAreas: ['SS4'],
  },
  {
    slug: 'barling',
    name: 'Barling',
    county: 'Essex',
    nearbyAreas: ['great-wakering', 'shoeburyness', 'rochford', 'foulness'],
    localHook: 'in the remote Barling Magna area',
    postcodeAreas: ['SS3'],
  },
  {
    slug: 'foulness',
    name: 'Foulness Island',
    county: 'Essex',
    nearbyAreas: ['great-wakering', 'barling', 'shoeburyness'],
    localHook: 'serving the remote island community',
    postcodeAreas: ['SS3'],
  },
  {
    slug: 'great-burstead',
    name: 'Great Burstead',
    county: 'Essex',
    nearbyAreas: ['billericay', 'basildon', 'wickford', 'stock'],
    localHook: 'throughout Great Burstead village',
    postcodeAreas: ['CM11'],
  },
  // Thurrock Additional
  {
    slug: 'purfleet',
    name: 'Purfleet',
    county: 'Essex',
    nearbyAreas: ['grays', 'rainham', 'west-thurrock', 'aveley'],
    localHook: 'across Purfleet and the Thames riverside',
    postcodeAreas: ['RM19'],
  },
  {
    slug: 'aveley',
    name: 'Aveley',
    county: 'Essex',
    nearbyAreas: ['south-ockendon', 'purfleet', 'rainham', 'grays'],
    localHook: 'throughout Aveley village',
    postcodeAreas: ['RM15'],
  },
  {
    slug: 'west-thurrock',
    name: 'West Thurrock',
    county: 'Essex',
    nearbyAreas: ['grays', 'purfleet', 'chafford-hundred', 'lakeside'],
    localHook: 'near the retail parks and industrial area',
    postcodeAreas: ['RM20'],
  },
  {
    slug: 'lakeside',
    name: 'Lakeside',
    county: 'Essex',
    nearbyAreas: ['chafford-hundred', 'west-thurrock', 'grays'],
    localHook: 'around the Lakeside shopping centre',
    postcodeAreas: ['RM20'],
  },
  {
    slug: 'orsett',
    name: 'Orsett',
    county: 'Essex',
    nearbyAreas: ['grays', 'stanford-le-hope', 'chadwell-st-mary', 'horndon-on-the-hill'],
    localHook: 'across the historic village',
    postcodeAreas: ['RM16'],
  },
  {
    slug: 'horndon-on-the-hill',
    name: 'Horndon on the Hill',
    county: 'Essex',
    nearbyAreas: ['stanford-le-hope', 'orsett', 'corringham', 'bulphan'],
    localHook: 'throughout the hilltop village',
    postcodeAreas: ['SS17'],
  },
  // Brentwood Additional
  {
    slug: 'pilgrims-hatch',
    name: 'Pilgrims Hatch',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'shenfield', 'doddinghurst', 'kelvedon-hatch'],
    localHook: 'across Pilgrims Hatch',
    postcodeAreas: ['CM15'],
  },
  {
    slug: 'warley',
    name: 'Warley',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'shenfield', 'hutton', 'childerditch'],
    localHook: 'throughout Great and Little Warley',
    postcodeAreas: ['CM13', 'CM14'],
  },
  {
    slug: 'ingrave',
    name: 'Ingrave',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'hutton', 'herongate', 'thorndon'],
    localHook: 'in the village near Thorndon Park',
    postcodeAreas: ['CM13'],
  },
  // Chelmsford Additional
  {
    slug: 'galleywood',
    name: 'Galleywood',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'great-baddow', 'stock', 'writtle'],
    localHook: 'across Galleywood Common and surroundings',
    postcodeAreas: ['CM2'],
  },
  {
    slug: 'great-waltham',
    name: 'Great Waltham',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'broomfield', 'little-waltham', 'pleshey'],
    localHook: 'throughout the historic village',
    postcodeAreas: ['CM3'],
  },
  {
    slug: 'little-waltham',
    name: 'Little Waltham',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'springfield', 'great-waltham', 'broomfield'],
    localHook: 'across the village and bypass area',
    postcodeAreas: ['CM3'],
  },
  {
    slug: 'boreham',
    name: 'Boreham',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'springfield', 'hatfield-peverel', 'little-baddow'],
    localHook: 'near the A12 and New Hall',
    postcodeAreas: ['CM3'],
  },
  {
    slug: 'sandon',
    name: 'Sandon',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'great-baddow', 'danbury', 'howe-green'],
    localHook: 'across Sandon village',
    postcodeAreas: ['CM2'],
  },
  {
    slug: 'terling',
    name: 'Terling',
    county: 'Essex',
    nearbyAreas: ['witham', 'hatfield-peverel', 'fairstead', 'braintree'],
    localHook: 'throughout the picturesque estate village',
    postcodeAreas: ['CM3'],
  },
  // Braintree Additional
  {
    slug: 'bocking',
    name: 'Bocking',
    county: 'Essex',
    nearbyAreas: ['braintree', 'halstead', 'gosfield', 'stisted'],
    localHook: 'across Bocking and Church Street',
    postcodeAreas: ['CM7'],
  },
  // Maldon Additional
  {
    slug: 'tollesbury',
    name: 'Tollesbury',
    county: 'Essex',
    nearbyAreas: ['maldon', 'tiptree', 'tolleshunt-darcy', 'salcott'],
    localHook: 'across the sailing village and marina',
    postcodeAreas: ['CM9'],
  },
  {
    slug: 'tolleshunt-darcy',
    name: "Tolleshunt D'Arcy",
    county: 'Essex',
    nearbyAreas: ['maldon', 'tollesbury', 'tiptree', 'heybridge'],
    localHook: 'throughout the rural village',
    postcodeAreas: ['CM9'],
  },
  {
    slug: 'goldhanger',
    name: 'Goldhanger',
    county: 'Essex',
    nearbyAreas: ['maldon', 'heybridge', 'tollesbury', 'osea-island'],
    localHook: 'along the Blackwater Estuary',
    postcodeAreas: ['CM9'],
  },
  {
    slug: 'tillingham',
    name: 'Tillingham',
    county: 'Essex',
    nearbyAreas: ['southminster', 'bradwell-on-sea', 'dengie', 'asheldham'],
    localHook: 'on the Dengie Peninsula',
    postcodeAreas: ['CM0'],
  },
  {
    slug: 'bradwell-on-sea',
    name: 'Bradwell-on-Sea',
    county: 'Essex',
    nearbyAreas: ['southminster', 'tillingham', 'maldon', 'burnham-on-crouch'],
    localHook: 'near the historic chapel and power station',
    postcodeAreas: ['CM0'],
  },
  // Tendring/Colchester Additional
  {
    slug: 'st-osyth',
    name: 'St Osyth',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'jaywick', 'brightlingsea', 'point-clear'],
    localHook: 'near the historic priory and holiday parks',
    postcodeAreas: ['CO16'],
  },
  {
    slug: 'great-bentley',
    name: 'Great Bentley',
    county: 'Essex',
    nearbyAreas: ['colchester', 'weeley', 'thorpe-le-soken', 'frating'],
    localHook: 'around the largest village green in England',
    postcodeAreas: ['CO7'],
  },
  {
    slug: 'great-bromley',
    name: 'Great Bromley',
    county: 'Essex',
    nearbyAreas: ['colchester', 'ardleigh', 'manningtree', 'little-bromley'],
    localHook: 'throughout the rural village',
    postcodeAreas: ['CO7'],
  },
  {
    slug: 'little-clacton',
    name: 'Little Clacton',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'weeley', 'thorpe-le-soken', 'great-clacton'],
    localHook: 'across the village centre',
    postcodeAreas: ['CO16'],
  },
  {
    slug: 'great-clacton',
    name: 'Great Clacton',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'holland-on-sea', 'little-clacton', 'jaywick'],
    localHook: 'throughout the inland Clacton area',
    postcodeAreas: ['CO15'],
  },
  {
    slug: 'lawford',
    name: 'Lawford',
    county: 'Essex',
    nearbyAreas: ['manningtree', 'mistley', 'dedham', 'ardleigh'],
    localHook: 'across Lawford and towards Manningtree',
    postcodeAreas: ['CO11'],
  },
  {
    slug: 'bradfield',
    name: 'Bradfield',
    county: 'Essex',
    nearbyAreas: ['manningtree', 'mistley', 'harwich', 'wrabness'],
    localHook: 'throughout Bradfield and the Stour Valley',
    postcodeAreas: ['CO11'],
  },
  {
    slug: 'parkeston',
    name: 'Parkeston',
    county: 'Essex',
    nearbyAreas: ['harwich', 'dovercourt', 'ramsey', 'wrabness'],
    localHook: 'near the quay and ferry terminal',
    postcodeAreas: ['CO12'],
  },
  {
    slug: 'ramsey',
    name: 'Ramsey',
    county: 'Essex',
    nearbyAreas: ['harwich', 'dovercourt', 'parkeston', 'little-oakley'],
    localHook: 'across Ramsey village',
    postcodeAreas: ['CO12'],
  },
  {
    slug: 'thorrington',
    name: 'Thorrington',
    county: 'Essex',
    nearbyAreas: ['brightlingsea', 'colchester', 'alresford', 'st-osyth'],
    localHook: 'throughout the village',
    postcodeAreas: ['CO7'],
  },
  {
    slug: 'alresford',
    name: 'Alresford',
    county: 'Essex',
    nearbyAreas: ['wivenhoe', 'colchester', 'brightlingsea', 'thorrington'],
    localHook: 'across the village and creek area',
    postcodeAreas: ['CO7'],
  },
  {
    slug: 'copford',
    name: 'Copford',
    county: 'Essex',
    nearbyAreas: ['colchester', 'stanway', 'marks-tey', 'easthorpe'],
    localHook: 'near the A12 and historic church',
    postcodeAreas: ['CO6'],
  },
  {
    slug: 'fordham',
    name: 'Fordham',
    county: 'Essex',
    nearbyAreas: ['colchester', 'west-bergholt', 'eight-ash-green', 'aldham'],
    localHook: 'throughout Fordham village',
    postcodeAreas: ['CO6'],
  },
  {
    slug: 'fingringhoe',
    name: 'Fingringhoe',
    county: 'Essex',
    nearbyAreas: ['colchester', 'rowhedge', 'abberton', 'langenhoe'],
    localHook: 'near the nature reserve and Roman River',
    postcodeAreas: ['CO5'],
  },
  {
    slug: 'abberton',
    name: 'Abberton',
    county: 'Essex',
    nearbyAreas: ['colchester', 'layer-de-la-haye', 'fingringhoe', 'peldon'],
    localHook: 'by the reservoir and nature reserve',
    postcodeAreas: ['CO5'],
  },
  {
    slug: 'birch',
    name: 'Birch',
    county: 'Essex',
    nearbyAreas: ['colchester', 'layer-de-la-haye', 'tiptree', 'copford'],
    localHook: 'across Birch and Layer Breton',
    postcodeAreas: ['CO2'],
  },
  {
    slug: 'langham',
    name: 'Langham',
    county: 'Essex',
    nearbyAreas: ['colchester', 'dedham', 'boxted', 'ardleigh'],
    localHook: 'in Constable Country',
    postcodeAreas: ['CO4'],
  },
  // West Essex Additional
  {
    slug: 'abridge',
    name: 'Abridge',
    county: 'Essex',
    nearbyAreas: ['theydon-bois', 'loughton', 'chigwell', 'stapleford-abbotts'],
    localHook: 'across the village by the River Roding',
    postcodeAreas: ['RM4'],
  },
  {
    slug: 'thornwood',
    name: 'Thornwood',
    county: 'Essex',
    nearbyAreas: ['epping', 'north-weald', 'harlow', 'coopersale'],
    localHook: 'throughout Thornwood Common',
    postcodeAreas: ['CM16'],
  },
  // Greater London Border Additional
  {
    slug: 'manor-park',
    name: 'Manor Park',
    county: 'Greater London',
    nearbyAreas: ['ilford', 'east-ham', 'forest-gate', 'woodgrange-park'],
    localHook: 'across Manor Park and Little Ilford',
    postcodeAreas: ['E12'],
  },
  // ===== Final Gap Closure: Remaining Small Villages =====
  // Basildon/South Essex villages
  {
    slug: 'langdon-hills',
    name: 'Langdon Hills',
    county: 'Essex',
    nearbyAreas: ['basildon', 'laindon', 'horndon-on-the-hill', 'stanford-le-hope'],
    localHook: 'across Langdon Hills Country Park area',
    postcodeAreas: ['SS16'],
  },
  {
    slug: 'rawreth',
    name: 'Rawreth',
    county: 'Essex',
    nearbyAreas: ['rayleigh', 'wickford', 'shotgate', 'battlesbridge'],
    localHook: 'throughout Rawreth village',
    postcodeAreas: ['SS11'],
  },
  {
    slug: 'battlesbridge',
    name: 'Battlesbridge',
    county: 'Essex',
    nearbyAreas: ['wickford', 'rawreth', 'rettendon', 'south-woodham-ferrers'],
    localHook: 'at the antiques centre and mill',
    postcodeAreas: ['SS11'],
  },
  {
    slug: 'canewdon',
    name: 'Canewdon',
    county: 'Essex',
    nearbyAreas: ['rochford', 'ashingdon', 'paglesham', 'wallasea'],
    localHook: 'on the hilltop overlooking the Crouch',
    postcodeAreas: ['SS4'],
  },
  // Thurrock/Brentwood villages
  {
    slug: 'bulphan',
    name: 'Bulphan',
    county: 'Essex',
    nearbyAreas: ['horndon-on-the-hill', 'orsett', 'stanford-le-hope', 'north-ockendon'],
    localHook: 'throughout the rural village',
    postcodeAreas: ['RM14'],
  },
  {
    slug: 'childerditch',
    name: 'Childerditch',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'warley', 'west-horndon', 'herongate'],
    localHook: 'in the Childerditch area',
    postcodeAreas: ['CM13'],
  },
  {
    slug: 'herongate',
    name: 'Herongate',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'ingrave', 'childerditch', 'east-horndon'],
    localHook: 'across Herongate village',
    postcodeAreas: ['CM13'],
  },
  {
    slug: 'thorndon',
    name: 'Thorndon',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'ingrave', 'herongate', 'childerditch'],
    localHook: 'near Thorndon Country Park',
    postcodeAreas: ['CM13'],
  },
  {
    slug: 'doddinghurst',
    name: 'Doddinghurst',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'pilgrims-hatch', 'kelvedon-hatch', 'ongar'],
    localHook: 'throughout Doddinghurst village',
    postcodeAreas: ['CM15'],
  },
  {
    slug: 'kelvedon-hatch',
    name: 'Kelvedon Hatch',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'doddinghurst', 'pilgrims-hatch', 'ongar'],
    localHook: 'near the Secret Nuclear Bunker',
    postcodeAreas: ['CM15'],
  },
  // Chelmsford villages
  {
    slug: 'pleshey',
    name: 'Pleshey',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'great-waltham', 'good-easter', 'high-easter'],
    localHook: 'around the historic castle motte',
    postcodeAreas: ['CM3'],
  },
  {
    slug: 'little-baddow',
    name: 'Little Baddow',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'danbury', 'boreham', 'sandon'],
    localHook: 'throughout the village and heathland',
    postcodeAreas: ['CM3'],
  },
  {
    slug: 'howe-green',
    name: 'Howe Green',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'sandon', 'great-baddow', 'rettendon'],
    localHook: 'in the Howe Green area',
    postcodeAreas: ['CM2'],
  },
  {
    slug: 'fairstead',
    name: 'Fairstead',
    county: 'Essex',
    nearbyAreas: ['witham', 'terling', 'braintree', 'faulkbourne'],
    localHook: 'throughout Fairstead village',
    postcodeAreas: ['CM3'],
  },
  // Braintree villages
  {
    slug: 'gosfield',
    name: 'Gosfield',
    county: 'Essex',
    nearbyAreas: ['halstead', 'braintree', 'bocking', 'sible-hedingham'],
    localHook: 'near Gosfield Lake and Hall',
    postcodeAreas: ['CO9'],
  },
  {
    slug: 'stisted',
    name: 'Stisted',
    county: 'Essex',
    nearbyAreas: ['braintree', 'bocking', 'coggeshall', 'witham'],
    localHook: 'throughout Stisted village',
    postcodeAreas: ['CM77'],
  },
  // Maldon/Dengie villages
  {
    slug: 'dengie',
    name: 'Dengie',
    county: 'Essex',
    nearbyAreas: ['southminster', 'tillingham', 'asheldham', 'bradwell-on-sea'],
    localHook: 'on the remote Dengie Peninsula',
    postcodeAreas: ['CM0'],
  },
  {
    slug: 'asheldham',
    name: 'Asheldham',
    county: 'Essex',
    nearbyAreas: ['southminster', 'tillingham', 'dengie', 'cold-norton'],
    localHook: 'in the Asheldham area',
    postcodeAreas: ['CM0'],
  },
  {
    slug: 'salcott',
    name: 'Salcott',
    county: 'Essex',
    nearbyAreas: ['tollesbury', 'maldon', 'virley', 'tolleshunt-knights'],
    localHook: 'near Salcott Creek',
    postcodeAreas: ['CM9'],
  },
  // Colchester/Tendring villages
  {
    slug: 'aldham',
    name: 'Aldham',
    county: 'Essex',
    nearbyAreas: ['colchester', 'fordham', 'marks-tey', 'copford'],
    localHook: 'throughout Aldham village',
    postcodeAreas: ['CO6'],
  },
  {
    slug: 'eight-ash-green',
    name: 'Eight Ash Green',
    county: 'Essex',
    nearbyAreas: ['colchester', 'fordham', 'stanway', 'copford'],
    localHook: 'across Eight Ash Green',
    postcodeAreas: ['CO6'],
  },
  {
    slug: 'easthorpe',
    name: 'Easthorpe',
    county: 'Essex',
    nearbyAreas: ['colchester', 'copford', 'marks-tey', 'messing'],
    localHook: 'in Easthorpe village',
    postcodeAreas: ['CO5'],
  },
  {
    slug: 'langenhoe',
    name: 'Langenhoe',
    county: 'Essex',
    nearbyAreas: ['colchester', 'fingringhoe', 'abberton', 'peldon'],
    localHook: 'across Langenhoe Marsh area',
    postcodeAreas: ['CO5'],
  },
  {
    slug: 'peldon',
    name: 'Peldon',
    county: 'Essex',
    nearbyAreas: ['colchester', 'abberton', 'west-mersea', 'langenhoe'],
    localHook: 'throughout Peldon village',
    postcodeAreas: ['CO5'],
  },
  {
    slug: 'frating',
    name: 'Frating',
    county: 'Essex',
    nearbyAreas: ['colchester', 'great-bentley', 'thorrington', 'elmstead'],
    localHook: 'in Frating village',
    postcodeAreas: ['CO7'],
  },
  {
    slug: 'little-bromley',
    name: 'Little Bromley',
    county: 'Essex',
    nearbyAreas: ['manningtree', 'great-bromley', 'ardleigh', 'lawford'],
    localHook: 'throughout Little Bromley',
    postcodeAreas: ['CO11'],
  },
  {
    slug: 'little-oakley',
    name: 'Little Oakley',
    county: 'Essex',
    nearbyAreas: ['harwich', 'ramsey', 'great-oakley', 'dovercourt'],
    localHook: 'in Little Oakley village',
    postcodeAreas: ['CO12'],
  },
  {
    slug: 'wrabness',
    name: 'Wrabness',
    county: 'Essex',
    nearbyAreas: ['harwich', 'parkeston', 'bradfield', 'ramsey'],
    localHook: 'on the Stour Estuary',
    postcodeAreas: ['CO11'],
  },
  {
    slug: 'point-clear',
    name: 'Point Clear',
    county: 'Essex',
    nearbyAreas: ['st-osyth', 'brightlingsea', 'jaywick', 'clacton-on-sea'],
    localHook: 'near the holiday parks',
    postcodeAreas: ['CO16'],
  },
  // West Essex villages
  {
    slug: 'coopersale',
    name: 'Coopersale',
    county: 'Essex',
    nearbyAreas: ['epping', 'thornwood', 'theydon-garnon', 'hobbs-cross'],
    localHook: 'in Coopersale village',
    postcodeAreas: ['CM16'],
  },
  {
    slug: 'stapleford-abbotts',
    name: 'Stapleford Abbotts',
    county: 'Essex',
    nearbyAreas: ['romford', 'abridge', 'lambourne', 'havering-atte-bower'],
    localHook: 'throughout Stapleford Abbotts',
    postcodeAreas: ['RM4'],
  },
  // Greater London border
  {
    slug: 'forest-gate',
    name: 'Forest Gate',
    county: 'Greater London',
    nearbyAreas: ['stratford', 'manor-park', 'east-ham', 'ilford'],
    localHook: 'across Forest Gate',
    postcodeAreas: ['E7'],
  },
  {
    slug: 'woodgrange-park',
    name: 'Woodgrange Park',
    county: 'Greater London',
    nearbyAreas: ['manor-park', 'forest-gate', 'east-ham', 'ilford'],
    localHook: 'in the Woodgrange Park area',
    postcodeAreas: ['E7', 'E12'],
  },
  // North Essex near Stansted
  {
    slug: 'sheering',
    name: 'Sheering',
    county: 'Essex',
    nearbyAreas: ['harlow', 'hatfield-heath', 'matching', 'hatfield-broad-oak'],
    localHook: 'in Sheering village',
    postcodeAreas: ['CM21'],
  },
  {
    slug: 'takeley',
    name: 'Takeley',
    county: 'Essex',
    nearbyAreas: ['stansted-mountfitchet', 'great-dunmow', 'great-hallingbury', 'sheering'],
    localHook: 'near Stansted Airport',
    postcodeAreas: ['CM22'],
  },
  {
    slug: 'great-hallingbury',
    name: 'Great Hallingbury',
    county: 'Essex',
    nearbyAreas: ['stansted-mountfitchet', 'takeley', 'great-dunmow', 'sheering'],
    localHook: 'throughout Great Hallingbury',
    postcodeAreas: ['CM22'],
  },
];

// Helper to get location by slug
export function getLocationBySlug(slug: string): Location | undefined {
  return locations.find((loc) => loc.slug === slug);
}

// Helper to get nearby locations as full objects
export function getNearbyLocations(location: Location): Location[] {
  return location.nearbyAreas
    .map((slug) => getLocationBySlug(slug))
    .filter((loc): loc is Location => loc !== undefined);
}

// Get all location slugs for static generation
export function getAllLocationSlugs(): string[] {
  return locations.map((loc) => loc.slug);
}
