// Location data for programmatic SEO
// Each location generates pages for all services (12 services × 61 locations = 732 pages)

export type Location = {
  slug: string;
  name: string;
  county: string;
  isCounty?: boolean; // true for county-level locations like Essex
  nearbyAreas: string[]; // slugs of nearby locations for internal linking
  localHook: string; // unique sentence fragment for content differentiation
  postcodeAreas?: string[]; // postcode coverage
  // Optional: area-specific pain points (drives conversions)
  commonProblems?: string[]; // e.g., "coastal salt residue", "clay soil stains"
};

export const locations: Location[] = [
  // County-level location (appears first for SEO priority)
  {
    slug: 'essex',
    name: 'Essex',
    county: 'Essex',
    isCounty: true,
    nearbyAreas: ['chelmsford', 'southend-on-sea', 'colchester', 'basildon', 'brentwood', 'harlow', 'romford', 'saffron-walden'],
    localHook: 'across the entire county from Southend to Harlow',
    commonProblems: ['coastal weather damage', 'rural mud and dirt', 'urban pollution buildup'],
  },
  {
    slug: 'basildon',
    name: 'Basildon',
    county: 'Essex',
    nearbyAreas: ['wickford', 'billericay', 'benfleet', 'canvey-island'],
    localHook: 'from Basildon town centre to Pitsea, Laindon, and Langdon Hills',
    postcodeAreas: ['SS13', 'SS14', 'SS15', 'SS16'],
    commonProblems: ['high foot traffic stains', 'pet odours', 'end of tenancy cleaning'],
  },
  {
    slug: 'southend-on-sea',
    name: 'Southend-on-Sea',
    county: 'Essex',
    nearbyAreas: ['westcliff-on-sea', 'leigh-on-sea', 'rochford', 'canvey-island'],
    localHook: 'from the seafront through Thorpe Bay, Prittlewell, and Shoeburyness',
    postcodeAreas: ['SS0', 'SS1', 'SS2', 'SS3', 'SS9'],
    commonProblems: ['salt residue from sea air', 'sand tracked indoors', 'seagull mess on roofs'],
  },
  {
    slug: 'chelmsford',
    name: 'Chelmsford',
    county: 'Essex',
    nearbyAreas: ['danbury', 'ingatestone', 'maldon', 'south-woodham-ferrers'],
    localHook: 'across the city centre including Springfield, Broomfield, Great Baddow, Writtle, and Galleywood',
    postcodeAreas: ['CM1', 'CM2', 'CM3'],
    commonProblems: ['moss and algae buildup', 'leaf stains on patios', 'clay soil marks'],
  },
  {
    slug: 'brentwood',
    name: 'Brentwood',
    county: 'Essex',
    nearbyAreas: ['billericay', 'ingatestone', 'ongar', 'chelmsford'],
    localHook: 'across Brentwood including Shenfield, Hutton, Warley, Pilgrims Hatch, and Ingrave',
    postcodeAreas: ['CM13', 'CM14', 'CM15'],
    commonProblems: ['large driveways needing refresh', 'tree sap on patios', 'green algae on render'],
  },
  {
    slug: 'billericay',
    name: 'Billericay',
    county: 'Essex',
    nearbyAreas: ['basildon', 'wickford', 'brentwood', 'ingatestone'],
    localHook: 'from the High Street to the surrounding residential areas',
    postcodeAreas: ['CM11', 'CM12'],
    commonProblems: ['moss on roof tiles', 'blocked gutters', 'weathered patio slabs'],
  },
  {
    slug: 'wickford',
    name: 'Wickford',
    county: 'Essex',
    nearbyAreas: ['basildon', 'rayleigh', 'billericay', 'south-woodham-ferrers'],
    localHook: 'across Wickford, Shotgate, and Battlesbridge',
    postcodeAreas: ['SS11', 'SS12'],
  },
  {
    slug: 'rayleigh',
    name: 'Rayleigh',
    county: 'Essex',
    nearbyAreas: ['hockley', 'rochford', 'wickford', 'benfleet'],
    localHook: 'across Rayleigh, Rawreth, and Hullbridge',
    postcodeAreas: ['SS6'],
  },
  {
    slug: 'benfleet',
    name: 'Benfleet',
    county: 'Essex',
    nearbyAreas: ['canvey-island', 'leigh-on-sea', 'rayleigh', 'basildon'],
    localHook: 'across Benfleet, South Benfleet, Thundersley, and Hadleigh',
    postcodeAreas: ['SS7'],
  },
  {
    slug: 'canvey-island',
    name: 'Canvey Island',
    county: 'Essex',
    nearbyAreas: ['benfleet', 'leigh-on-sea', 'basildon'],
    localHook: 'across the entire island community',
    postcodeAreas: ['SS8'],
    commonProblems: ['island flooding risk leaving silt on ground floors', 'sea wall salt spray on windows', 'estuary damp accelerating mould indoors'],
  },
  {
    slug: 'grays',
    name: 'Grays',
    county: 'Essex',
    nearbyAreas: ['tilbury', 'stanford-le-hope', 'upminster', 'rainham'],
    localHook: 'throughout Grays, Chafford Hundred, South Ockendon, Purfleet, and Lakeside',
    postcodeAreas: ['RM17', 'RM20'],
    commonProblems: ['A13 traffic soot settling on render', 'Thames-side humidity accelerating mould', 'industrial area dust coating windows'],
  },
  {
    slug: 'stanford-le-hope',
    name: 'Stanford-le-Hope',
    county: 'Essex',
    nearbyAreas: ['grays', 'tilbury', 'basildon', 'upminster'],
    localHook: 'serving Stanford-le-Hope, Corringham, and Horndon on the Hill',
    postcodeAreas: ['SS17'],
  },
  {
    slug: 'tilbury',
    name: 'Tilbury',
    county: 'Essex',
    nearbyAreas: ['grays', 'stanford-le-hope', 'basildon'],
    localHook: 'across Tilbury and Chadwell St Mary',
    postcodeAreas: ['RM18'],
  },
  {
    slug: 'leigh-on-sea',
    name: 'Leigh-on-Sea',
    county: 'Essex',
    nearbyAreas: ['southend-on-sea', 'westcliff-on-sea', 'benfleet', 'rayleigh'],
    localHook: 'from Old Leigh to the Broadway',
    postcodeAreas: ['SS9'],
    commonProblems: ['Old Leigh harbour salt air on windows', 'sand tracked up from the beach into carpets', 'seafront damp accelerating patio moss'],
  },
  {
    slug: 'westcliff-on-sea',
    name: 'Westcliff-on-Sea',
    county: 'Essex',
    nearbyAreas: ['southend-on-sea', 'leigh-on-sea', 'rochford'],
    localHook: 'along the clifftop and surrounding streets',
    postcodeAreas: ['SS0'],
    commonProblems: ['clifftop wind driving salt onto render', 'sea air damp causing window frame grime', 'north-facing cliffs trapping moss on walls'],
  },
  {
    slug: 'rochford',
    name: 'Rochford',
    county: 'Essex',
    nearbyAreas: ['rayleigh', 'hockley', 'southend-on-sea', 'wickford'],
    localHook: 'throughout Rochford, Ashingdon, Canewdon, and Great Wakering',
    postcodeAreas: ['SS4'],
    commonProblems: ['river Roach damp encouraging indoor mould', 'market town foot traffic wearing shop carpets', 'low-lying area flooding leaving mud residue'],
  },
  {
    slug: 'hockley',
    name: 'Hockley',
    county: 'Essex',
    nearbyAreas: ['rayleigh', 'rochford', 'wickford', 'southend-on-sea'],
    localHook: 'across Hockley and Hawkwell',
    postcodeAreas: ['SS5'],
  },
  {
    slug: 'maldon',
    name: 'Maldon',
    county: 'Essex',
    nearbyAreas: ['burnham-on-crouch', 'witham', 'danbury', 'chelmsford'],
    localHook: 'across Maldon, Heybridge, Tollesbury, and the Blackwater Estuary villages',
    postcodeAreas: ['CM9'],
    commonProblems: ['Blackwater estuary salt air on windows', 'Hythe waterfront humidity accelerating algae', 'tidal mud tracked from riverside walks'],
  },
  {
    slug: 'witham',
    name: 'Witham',
    county: 'Essex',
    nearbyAreas: ['braintree', 'maldon', 'tiptree', 'chelmsford'],
    localHook: 'across Witham, Kelvedon, Hatfield Peverel, and Terling',
    postcodeAreas: ['CM8'],
  },
  {
    slug: 'braintree',
    name: 'Braintree',
    county: 'Essex',
    nearbyAreas: ['witham', 'halstead', 'coggeshall', 'colchester'],
    localHook: 'across Braintree and Bocking',
    postcodeAreas: ['CM7'],
  },
  {
    slug: 'colchester',
    name: 'Colchester',
    county: 'Essex',
    nearbyAreas: ['wivenhoe', 'west-mersea', 'brightlingsea', 'dedham', 'tiptree', 'manningtree', 'clacton-on-sea', 'witham'],
    localHook: 'across Colchester including Stanway, Marks Tey, Layer-de-la-Haye, and surrounding villages',
    postcodeAreas: ['CO1', 'CO2', 'CO3', 'CO4'],
    commonProblems: ['Roman wall stonework staining', 'university term-end carpet wear', 'garrison area soot buildup'],
  },
  {
    slug: 'clacton-on-sea',
    name: 'Clacton-on-Sea',
    county: 'Essex',
    nearbyAreas: ['frinton-on-sea', 'walton-on-the-naze', 'colchester', 'brightlingsea'],
    localHook: 'from the seafront through Jaywick, Holland-on-Sea, St Osyth, and Great Clacton',
    postcodeAreas: ['CO15', 'CO16'],
    commonProblems: ['sea salt film on windows and frames', 'beach sand tracked deep into hallway carpets', 'coastal damp feeding moss on north-facing roofs'],
  },
  {
    slug: 'harlow',
    name: 'Harlow',
    county: 'Essex',
    nearbyAreas: ['epping', 'ongar', 'stansted-mountfitchet'],
    localHook: 'across Harlow including North Weald and Sheering',
    postcodeAreas: ['CM17', 'CM18', 'CM19', 'CM20'],
    commonProblems: ['new town block paving sprouting weeds fast', 'construction dust in recently built homes', 'flat terrain rain pooling causing patio algae'],
  },
  {
    slug: 'epping',
    name: 'Epping',
    county: 'Essex',
    nearbyAreas: ['harlow', 'loughton', 'ongar', 'waltham-abbey'],
    localHook: 'across Epping, Theydon Bois, Thornwood, and Coopersale',
    postcodeAreas: ['CM16'],
    commonProblems: ['Epping Forest leaf fall clogging gutters', 'tree canopy shade accelerating roof moss', 'forest pollen coating windows and driveways'],
  },
  {
    slug: 'loughton',
    name: 'Loughton',
    county: 'Essex',
    nearbyAreas: ['chigwell', 'buckhurst-hill', 'epping', 'woodford', 'waltham-abbey'],
    localHook: 'throughout Loughton, Debden, and Abridge',
    postcodeAreas: ['IG10'],
    commonProblems: ['forest-edge leaf debris blocking gutters every autumn', 'tree canopy shade driving moss on north-facing roofs', 'sap and bird droppings staining driveways'],
  },
  {
    slug: 'chigwell',
    name: 'Chigwell',
    county: 'Essex',
    nearbyAreas: ['loughton', 'woodford', 'buckhurst-hill', 'ilford'],
    localHook: 'across Chigwell and Grange Hill',
    postcodeAreas: ['IG7', 'IG8'],
    commonProblems: ['tree-lined roads shedding leaves into gutters', 'sap and pollen staining block paving', 'shade from mature gardens causing rapid moss growth'],
  },
  // Additional Essex Towns
  {
    slug: 'saffron-walden',
    name: 'Saffron Walden',
    county: 'Essex',
    nearbyAreas: ['great-dunmow', 'braintree', 'halstead'],
    localHook: 'throughout the historic market town and surrounding villages',
    postcodeAreas: ['CB10', 'CB11'],
    commonProblems: ['thatched roof moss and lichen', 'lime mortar sensitivity on old walls', 'pollen buildup from surrounding farmland'],
  },
  {
    slug: 'great-dunmow',
    name: 'Great Dunmow',
    county: 'Essex',
    nearbyAreas: ['saffron-walden', 'braintree', 'chelmsford', 'harlow'],
    localHook: 'across the town and nearby villages',
    postcodeAreas: ['CM6'],
  },
  {
    slug: 'halstead',
    name: 'Halstead',
    county: 'Essex',
    nearbyAreas: ['braintree', 'colchester', 'saffron-walden'],
    localHook: 'throughout Halstead, Gosfield, and the Colne Valley',
    postcodeAreas: ['CO9'],
  },
  {
    slug: 'burnham-on-crouch',
    name: 'Burnham-on-Crouch',
    county: 'Essex',
    nearbyAreas: ['maldon', 'rochford', 'south-woodham-ferrers', 'chelmsford'],
    localHook: 'across Burnham-on-Crouch, Southminster, Bradwell-on-Sea, and the Dengie Peninsula',
    postcodeAreas: ['CM0'],
    commonProblems: ['Crouch estuary salt air corroding gutters', 'river humidity accelerating algae on render', 'tidal mud tracked from waterfront onto floors'],
  },
  {
    slug: 'frinton-on-sea',
    name: 'Frinton-on-Sea',
    county: 'Essex',
    nearbyAreas: ['clacton-on-sea', 'walton-on-the-naze', 'colchester'],
    localHook: 'from the Greensward to the residential streets',
    postcodeAreas: ['CO13'],
    commonProblems: ['sea salt damage', 'sand accumulation', 'coastal weather exposure'],
  },
  {
    slug: 'walton-on-the-naze',
    name: 'Walton-on-the-Naze',
    county: 'Essex',
    nearbyAreas: ['frinton-on-sea', 'clacton-on-sea', 'colchester'],
    localHook: 'across the seaside town and surrounding area',
    postcodeAreas: ['CO14'],
    commonProblems: ['Naze cliff salt spray corroding gutters', 'coastal wind driving sand into carpet pile', 'seafront humidity accelerating roof moss'],
  },
  {
    slug: 'manningtree',
    name: 'Manningtree',
    county: 'Essex',
    nearbyAreas: ['colchester', 'harwich', 'dedham', 'clacton-on-sea'],
    localHook: 'across Manningtree, Mistley, Lawford, and the Stour Valley',
    postcodeAreas: ['CO11'],
  },
  // Colchester area locations
  {
    slug: 'wivenhoe',
    name: 'Wivenhoe',
    county: 'Essex',
    nearbyAreas: ['colchester', 'brightlingsea', 'west-mersea', 'clacton-on-sea'],
    localHook: 'across the historic port town and university area',
    postcodeAreas: ['CO7'],
    commonProblems: ['river Colne damp causing indoor mould', 'student flat end-of-tenancy carpet stains', 'tidal mud tracked onto driveways'],
  },
  {
    slug: 'west-mersea',
    name: 'West Mersea',
    county: 'Essex',
    nearbyAreas: ['colchester', 'brightlingsea', 'maldon', 'clacton-on-sea'],
    localHook: 'across Mersea Island and the waterfront',
    postcodeAreas: ['CO5'],
    commonProblems: ['salt spray corroding guttering', 'coastal wind driving sand into carpet pile', 'island humidity accelerating moss growth'],
  },
  {
    slug: 'brightlingsea',
    name: 'Brightlingsea',
    county: 'Essex',
    nearbyAreas: ['colchester', 'wivenhoe', 'west-mersea', 'clacton-on-sea'],
    localHook: 'across the sailing town and harbour area',
    postcodeAreas: ['CO7'],
    commonProblems: ['harbour salt spray on windows', 'algae growth from estuary humidity', 'boat yard dust settling on patios'],
  },
  {
    slug: 'dedham',
    name: 'Dedham',
    county: 'Essex',
    nearbyAreas: ['colchester', 'manningtree', 'harwich', 'brightlingsea'],
    localHook: 'in the heart of Constable Country',
    postcodeAreas: ['CO7'],
    commonProblems: ['river Stour damp encouraging moss on roofs', 'country lane mud tracked onto floors', 'listed building lime mortar sensitivity'],
  },
  {
    slug: 'waltham-abbey',
    name: 'Waltham Abbey',
    county: 'Essex',
    nearbyAreas: ['epping', 'loughton', 'chingford', 'woodford'],
    localHook: 'from the historic abbey to modern estates',
    postcodeAreas: ['EN9'],
  },
  {
    slug: 'ingatestone',
    name: 'Ingatestone',
    county: 'Essex',
    nearbyAreas: ['brentwood', 'chelmsford', 'billericay'],
    localHook: 'across the village and surrounding countryside',
    postcodeAreas: ['CM4'],
  },
  {
    slug: 'south-woodham-ferrers',
    name: 'South Woodham Ferrers',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'maldon', 'wickford', 'burnham-on-crouch'],
    localHook: 'throughout the town and riverside areas',
    postcodeAreas: ['CM3'],
  },
  // Greater London Border Areas
  {
    slug: 'romford',
    name: 'Romford',
    county: 'Greater London',
    nearbyAreas: ['hornchurch', 'upminster', 'ilford', 'dagenham', 'brentwood'],
    localHook: 'across Romford, Stapleford Abbotts, and the Borough of Havering',
    postcodeAreas: ['RM1', 'RM2', 'RM3', 'RM7'],
    commonProblems: ['A12 traffic soot on render and fascias', 'high street pollution film on shop fronts', 'heavy foot traffic staining entrance carpets'],
  },
  {
    slug: 'hornchurch',
    name: 'Hornchurch',
    county: 'Greater London',
    nearbyAreas: ['romford', 'upminster', 'rainham', 'dagenham'],
    localHook: 'throughout Hornchurch and Emerson Park',
    postcodeAreas: ['RM11', 'RM12'],
  },
  {
    slug: 'upminster',
    name: 'Upminster',
    county: 'Greater London',
    nearbyAreas: ['hornchurch', 'romford', 'grays', 'stanford-le-hope'],
    localHook: 'across Upminster and Cranham',
    postcodeAreas: ['RM14'],
  },
  {
    slug: 'ilford',
    name: 'Ilford',
    county: 'Greater London',
    nearbyAreas: ['romford', 'barking', 'woodford', 'chigwell', 'east-ham'],
    localHook: 'across Ilford, Manor Park, Hainault, and the Borough of Redbridge',
    postcodeAreas: ['IG1', 'IG2', 'IG3', 'IG4', 'IG5', 'IG6'],
    commonProblems: ['traffic pollution grime on windows', 'road salt staining driveways in winter', 'high-density housing trapping damp and mould'],
  },
  {
    slug: 'woodford',
    name: 'Woodford',
    county: 'Greater London',
    nearbyAreas: ['loughton', 'chigwell', 'ilford', 'wanstead'],
    localHook: 'throughout Woodford Green and South Woodford',
    postcodeAreas: ['IG8', 'E18'],
    commonProblems: ['tree-lined streets clogging gutters with leaves', 'forest-edge shade driving algae on fences', 'mature garden debris staining patios'],
  },
  {
    slug: 'barking',
    name: 'Barking',
    county: 'Greater London',
    nearbyAreas: ['dagenham', 'ilford', 'romford', 'east-ham'],
    localHook: 'across Barking and the surrounding area',
    postcodeAreas: ['IG11'],
  },
  {
    slug: 'dagenham',
    name: 'Dagenham',
    county: 'Greater London',
    nearbyAreas: ['barking', 'romford', 'hornchurch', 'rainham'],
    localHook: 'throughout Dagenham and Becontree',
    postcodeAreas: ['RM8', 'RM9', 'RM10'],
  },
  // More Local Essex Towns
  {
    slug: 'ongar',
    name: 'Ongar',
    county: 'Essex',
    nearbyAreas: ['epping', 'brentwood', 'harlow', 'ingatestone'],
    localHook: 'across Chipping Ongar and the surrounding villages',
    postcodeAreas: ['CM5'],
  },
  {
    slug: 'stansted-mountfitchet',
    name: 'Stansted Mountfitchet',
    county: 'Essex',
    nearbyAreas: ['saffron-walden', 'great-dunmow', 'harlow'],
    localHook: 'across Stansted Mountfitchet, Takeley, and near Stansted Airport',
    postcodeAreas: ['CM24'],
  },
  {
    slug: 'tiptree',
    name: 'Tiptree',
    county: 'Essex',
    nearbyAreas: ['colchester', 'witham', 'maldon', 'braintree'],
    localHook: 'across Tiptree and the surrounding area',
    postcodeAreas: ['CO5'],
  },
  {
    slug: 'danbury',
    name: 'Danbury',
    county: 'Essex',
    nearbyAreas: ['chelmsford', 'maldon', 'south-woodham-ferrers', 'ingatestone'],
    localHook: 'across Danbury, Little Baddow, and the surrounding countryside',
    postcodeAreas: ['CM3'],
    commonProblems: ['hilltop wind exposure driving rain into render', 'dense woodland leaf fall clogging gutters', 'clay soil staining driveways after heavy rain'],
  },
  // East London Areas
  {
    slug: 'stratford',
    name: 'Stratford',
    county: 'Greater London',
    nearbyAreas: ['leyton', 'east-ham', 'ilford', 'wanstead'],
    localHook: 'across Stratford, Woodgrange Park, and the Olympic Park area',
    postcodeAreas: ['E15', 'E20'],
    commonProblems: ['post-construction dust in new-build carpets', 'Olympic Park pollen and tree debris', 'high-rise window grime from city air'],
  },
  {
    slug: 'walthamstow',
    name: 'Walthamstow',
    county: 'Greater London',
    nearbyAreas: ['leyton', 'chingford', 'woodford', 'ilford'],
    localHook: 'from the Village to Blackhorse Road',
    postcodeAreas: ['E17'],
    commonProblems: ['Victorian sash window grime buildup', 'narrow street trapping moss on north walls', 'market area foot traffic wearing carpets fast'],
  },
  {
    slug: 'leyton',
    name: 'Leyton',
    county: 'Greater London',
    nearbyAreas: ['wanstead', 'stratford', 'walthamstow', 'east-ham'],
    localHook: 'throughout Leyton, Leytonstone, and the surrounding area',
    postcodeAreas: ['E10'],
  },
  {
    slug: 'east-ham',
    name: 'East Ham',
    county: 'Greater London',
    nearbyAreas: ['barking', 'stratford', 'ilford', 'wanstead'],
    localHook: 'throughout East Ham, Forest Gate, and the surrounding streets',
    postcodeAreas: ['E6'],
  },
  {
    slug: 'wanstead',
    name: 'Wanstead',
    county: 'Greater London',
    nearbyAreas: ['ilford', 'leyton', 'woodford', 'chigwell'],
    localHook: 'across Wanstead and Snaresbrook',
    postcodeAreas: ['E11'],
  },
  // High Priority Additions
  {
    slug: 'harwich',
    name: 'Harwich',
    county: 'Essex',
    nearbyAreas: ['manningtree', 'colchester', 'frinton-on-sea', 'walton-on-the-naze'],
    localHook: 'across Harwich, Dovercourt, Parkeston, and Ramsey',
    postcodeAreas: ['CO12'],
    commonProblems: ['sea salt corrosion', 'ferry traffic pollution', 'coastal weather exposure'],
  },
  {
    slug: 'buckhurst-hill',
    name: 'Buckhurst Hill',
    county: 'Essex',
    nearbyAreas: ['loughton', 'chigwell', 'woodford', 'epping'],
    localHook: 'throughout the affluent commuter town',
    postcodeAreas: ['IG9'],
    commonProblems: ['tree canopy shedding leaves into gutters', 'forest shade causing moss on roof tiles', 'sap and pollen staining driveways'],
  },
  {
    slug: 'chingford',
    name: 'Chingford',
    county: 'Greater London',
    nearbyAreas: ['walthamstow', 'loughton', 'woodford', 'buckhurst-hill'],
    localHook: 'from Chingford Mount to the Epping Forest edge',
    postcodeAreas: ['E4'],
    commonProblems: ['Epping Forest leaf fall blocking gutters', 'tree shade driving green algae on render', 'forest pollen coating conservatory glass'],
  },
  {
    slug: 'rainham',
    name: 'Rainham',
    county: 'Greater London',
    nearbyAreas: ['hornchurch', 'dagenham', 'grays', 'barking'],
    localHook: 'across Rainham and the marshes area',
    postcodeAreas: ['RM13'],
    commonProblems: ['industrial fallout film on windows', 'marshland damp accelerating mould growth', 'Thames-side salt air corroding guttering'],
  },
  {
    slug: 'coggeshall',
    name: 'Coggeshall',
    county: 'Essex',
    nearbyAreas: ['braintree', 'colchester', 'witham', 'tiptree'],
    localHook: 'throughout the historic wool town',
    postcodeAreas: ['CO6'],
    commonProblems: ['timber-framed buildings trapping damp and mould', 'narrow street moss on shaded walls', 'Colne Valley humidity staining render'],
  },
];

// Helper to get location by slug
export function getLocationBySlug(slug: string): Location | undefined {
  return locations.find((loc) => loc.slug === slug);
}

// Helper to get nearby locations as full objects
export function getNearbyLocations(location: Location): Location[] {
  return location.nearbyAreas
    .map((slug) => getLocationBySlug(slug))
    .filter((loc): loc is Location => loc !== undefined);
}

// Get all location slugs for static generation
export function getAllLocationSlugs(): string[] {
  return locations.map((loc) => loc.slug);
}
